# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_auto_20160519_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='modefied',
            field=models.DateTimeField(),
        ),
    ]
