# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0005_auto_20160520_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='modefied',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
