# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 21:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0006_auto_20160520_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='age',
        ),
        migrations.AddField(
            model_name='director',
            name='birth_day',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
