# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0008_auto_20160523_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='release_date',
            field=models.DateField(auto_now=True),
        ),
    ]
