# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 04:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0009_auto_20160525_0340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'permissions': (('restrict_some_action', 'Restrict some action'), ('Restrict_another_action', 'Restrict another action'))},
        ),
    ]
